import { chromium } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { products } from '../src/catalog.js'
import { commerceLandingPages, journalArticles, seoLandingPages } from '../src/seoContent.js'

const externalURL = process.env.BASE_URL
const baseURL = externalURL || 'http://127.0.0.1:4177'
let server
let browser

async function waitForServer(url, attempts = 50) {
  for (let i = 0; i < attempts; i++) {
    try { if ((await fetch(url)).ok) return } catch {}
    await new Promise(resolve => setTimeout(resolve, 150))
  }
  throw new Error(`QA server did not become ready at ${url}`)
}

async function auditAccessibility(page,label) {
  const results=await new AxeBuilder({page}).analyze()
  const serious=results.violations
  assert.equal(serious.length,0,`${label} accessibility:\n${serious.map(item=>`${item.id} (${item.nodes.length})\n${item.nodes.slice(0,8).map(node=>`  ${node.target.join(' ')} — ${node.failureSummary}`).join('\n')}`).join('\n')}`)
}

try {
  if (!externalURL) {
    server = spawn('npm', ['run', 'dev', '--', '--port', '4177'], { cwd: process.cwd(), stdio: 'ignore', detached: true })
    await waitForServer(baseURL)
  }

  browser = await chromium.launch({ headless: true })
  const desktopContext = await browser.newContext({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 })
  const page = await desktopContext.newPage()
  const errors = []
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()) })
  page.on('pageerror', err => errors.push(err.message))

  await page.goto(baseURL, { waitUntil: 'networkidle' })
  assert.match(await page.title(), /MoroKika/)
  assert.match(await page.locator('meta[name="description"]').getAttribute('content'), /pâtisserie artisanale/i)
  const manifestResponse=await page.request.get(`${baseURL}/manifest.webmanifest`)
  assert.ok(manifestResponse.ok())
  const manifest=await manifestResponse.json()
  assert.equal(manifest.icons.length,3)
  for(const icon of manifest.icons) assert.ok((await page.request.get(`${baseURL}${icon.src}`)).ok(),`Missing PWA icon ${icon.src}`)
  const serviceWorkerResponse=await page.request.get(`${baseURL}/sw.js`)
  assert.ok(serviceWorkerResponse.ok())
  assert.match(await serviceWorkerResponse.text(),/morokika-store-v7/)
  assert.ok((await page.request.get(`${baseURL}/sitemap.xml`)).ok())
  assert.ok((await page.request.get(`${baseURL}/robots.txt`)).ok())
  assert.equal(await page.locator('link[rel="canonical"]').getAttribute('href'),'https://morokika.netlify.app/')
  assert.equal(await page.locator('meta[property="og:image"]').getAttribute('content'),'https://morokika.netlify.app/images/hero-cake.webp')
  assert.equal(await page.locator('meta[name="robots"]').getAttribute('content'),'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1')
  await page.screenshot({ path: 'tests/home-desktop.png', fullPage: true })
  await auditAccessibility(page,'Home')
  await page.getByRole('button',{name:'Rechercher'}).click()
  await page.getByLabel('Rechercher un gâteau').fill('Pistache')
  assert.ok(await page.locator('.search-results').isVisible())
  await page.waitForTimeout(350)
  await auditAccessibility(page,'Search dialog')
  await page.keyboard.press('Escape')
  assert.ok(await page.locator('.search-overlay:not(.open)').isVisible())

  await page.goto(`${baseURL}/sur-mesure`, { waitUntil:'networkidle' })
  assert.ok(await page.getByRole('heading', { name:/Racontez-nous votre occasion/ }).isVisible())
  await auditAccessibility(page,'Custom cake')
  await page.locator('.occasion-grid button').filter({hasText:'Mariage'}).click()
  await page.getByRole('button', { name:/Continuer/ }).click()
  await page.getByRole('button', { name:/Vanille & fruits rouges/ }).click()
  await page.getByRole('button', { name:/Continuer/ }).click()
  await page.getByLabel('Votre nom').fill('Nadia Test')
  await page.getByLabel('Téléphone').fill('0612345678')
  await page.getByLabel('Adresse e-mail').fill('nadia@example.ma')
  await page.getByRole('button', { name:/Envoyer ma demande/ }).click()
  assert.ok(await page.getByRole('heading', { name:/Votre idée est entre de bonnes mains/ }).isVisible())
  const savedBrief=await page.evaluate(()=>JSON.parse(localStorage.getItem('morokika-admin-briefs'))[0])
  assert.equal(savedBrief.name,'Nadia Test')
  assert.equal(savedBrief.status,'Nouvelle')

  await page.goto(`${baseURL}/cgv`, { waitUntil:'networkidle' })
  assert.ok(await page.getByRole('heading', { name:'Conditions générales de vente' }).isVisible())
  await auditAccessibility(page,'Legal')

  const commerceRoutes=commerceLandingPages.map(page=>page.path)
  const staticProductSlugs=products.map(product=>product.id)
  const seoRoutes=seoLandingPages.map(page=>page.path)
  const articleRoutes=journalArticles.map(article=>`/journal/${article.slug}`)
  const sitemap=await (await page.request.get(`${baseURL}/sitemap.xml`)).text()
  const priorityArticleRoutes=articleRoutes
  for(const route of [...seoRoutes,...priorityArticleRoutes]) assert.ok(sitemap.includes(`https://morokika.netlify.app${route}</loc>`),`${route} missing from sitemap`)
  if(existsSync('dist/gateaux-rabat/index.html')) for(const route of [...seoRoutes,...priorityArticleRoutes]) {
    const staticHtml=readFileSync(`dist${route}/index.html`,'utf8')
    assert.ok(staticHtml.includes(`rel="canonical" href="https://morokika.netlify.app${route}"`),`${route} static canonical missing`)
    assert.ok(staticHtml.includes(`hreflang="fr-MA" href="https://morokika.netlify.app${route}"`),`${route} static hreflang missing`)
    assert.ok(staticHtml.includes(`data-static-route="${route}"`),`${route} static content missing`)
    assert.ok(staticHtml.includes('id="static-route-schema"'),`${route} static schema missing`)
    assert.ok(staticHtml.split(/\s+/).length>340,`${route} static HTML is too thin`)
  }
  if(existsSync('dist/boutique/index.html')) for(const route of commerceRoutes) {
    const staticHtml=readFileSync(`dist${route}/index.html`,'utf8')
    assert.ok(staticHtml.includes(`data-static-route="${route}"`),`${route} static collection content missing`)
    assert.ok(staticHtml.includes('CollectionPage')&&staticHtml.includes('ItemList'),`${route} static collection schema missing`)
  }
  if(existsSync('dist/produit/pistache-fleur-doranger/index.html')) for(const slug of staticProductSlugs) {
    const route=`/produit/${slug}`
    const staticHtml=readFileSync(`dist${route}/index.html`,'utf8')
    assert.ok(sitemap.includes(`https://morokika.netlify.app${route}</loc>`),`${route} missing from sitemap`)
    assert.ok(staticHtml.includes(`data-static-route="${route}"`),`${route} static product content missing`)
    assert.ok(staticHtml.includes('Product')&&staticHtml.includes('BreadcrumbList'),`${route} static product schema missing`)
    assert.ok(staticHtml.includes('product-practical'),`${route} static practical guidance missing`)
    assert.ok(!staticHtml.includes('schema.org/InStock'),`${route} must not claim stock availability when stock is untracked`)
  }
  const contentRoutes=['/boutique','/la-maison','/journal',...articleRoutes,'/livraison','/guide-des-tailles','/allergenes','/contact','/faq','/collections/signatures','/collections/anniversaires','/collections/cadeaux',...seoRoutes]
  for (const route of contentRoutes) {
    await page.goto(`${baseURL}${route}`, { waitUntil:'networkidle' })
    assert.equal(await page.locator('h1').count(),1,`${route} should have one H1`)
    assert.equal(await page.locator('link[rel="canonical"]').getAttribute('href'),`https://morokika.netlify.app${route}`)
    assert.equal(await page.locator('link[hreflang="fr-MA"]').getAttribute('href'),`https://morokika.netlify.app${route}`)
    if(commerceRoutes.includes(route)) assert.equal(await page.locator('#commerce-schema').count(),1)
    if(seoRoutes.includes(route)) {
      assert.equal(await page.locator('#seo-landing-schema').count(),1)
      const schema=JSON.parse(await page.locator('#seo-landing-schema').textContent())
      assert.equal(schema['@graph'].length,3)
      assert.ok((await page.locator('main').innerText()).split(/\s+/).length>350,`${route} needs substantial copy`)
    }
    if(route==='/faq') {
      assert.equal(await page.locator('#core-page-schema').count(),1)
      const schema=JSON.parse(await page.locator('#core-page-schema').textContent())
      assert.equal(schema['@graph'].find(item=>item['@type']==='FAQPage').mainEntity.length,9)
    }
    assert.ok((await page.locator('main').innerText()).split(/\s+/).length>350,`${route} needs substantial visible copy`)
    if(route.startsWith('/journal/')) {
      assert.equal(await page.locator('#article-schema').count(),1)
      assert.equal(await page.locator('#article-breadcrumb-schema').count(),1)
      const schema=JSON.parse(await page.locator('#article-schema').textContent())
      assert.match(schema.image,/^https:\/\/morokika\.netlify\.app\/images\//)
      assert.match(schema.datePublished,/^2026-/)
      assert.equal(schema.inLanguage,'fr-MA')
      assert.ok(schema.wordCount>300)
    }
    await auditAccessibility(page,route)
  }

  for(const slug of staticProductSlugs){
    const route=`/produit/${slug}`
    await page.goto(`${baseURL}${route}`,{waitUntil:'networkidle'})
    assert.equal(await page.locator('h1').count(),1,`${route} should have one H1`)
    assert.equal(await page.locator('link[rel="canonical"]').getAttribute('href'),`https://morokika.netlify.app${route}`)
    assert.equal(await page.locator('#product-schema').count(),1)
    assert.equal(await page.locator('#product-breadcrumb-schema').count(),1)
    assert.equal(await page.locator('.product-editorial article').count(),3)
    assert.equal(await page.locator('.product-practical article').count(),3)
    assert.ok((await page.locator('main').innerText()).split(/\s+/).length>450,`${route} needs substantial product guidance`)
    assert.equal(JSON.parse(await page.locator('#product-schema').textContent()).offers.availability,undefined)
  }

  for(const route of ['/confidentialite','/cgv','/mentions-legales']){
    await page.goto(`${baseURL}${route}`,{waitUntil:'networkidle'})
    assert.equal(await page.locator('h1').count(),1)
    assert.equal(await page.locator('link[rel="canonical"]').getAttribute('href'),`https://morokika.netlify.app${route}`)
    assert.equal(await page.locator('#core-page-schema').count(),1)
    assert.ok((await page.locator('main').innerText()).split(/\s+/).length>350,`${route} needs substantial visible copy`)
    await auditAccessibility(page,route)
  }

  await page.goto(`${baseURL}/contact`, { waitUntil:'networkidle' })
  await page.getByLabel('Votre nom').fill('Nadia Test')
  await page.getByLabel('Adresse e-mail').fill('nadia@example.ma')
  await page.getByLabel('Votre message').fill('Bonjour, je souhaite confirmer vos horaires de retrait.')
  await page.getByRole('button',{name:/Envoyer mon message/}).click()
  assert.ok(await page.getByRole('heading',{name:'Message bien envoyé'}).isVisible())

  await page.goto(`${baseURL}/faq`, { waitUntil:'networkidle' })
  await page.getByRole('button',{name:/Combien de temps/}).click()
  assert.ok(await page.getByText(/Nous conseillons 48 heures/).isVisible())

  await page.evaluate(()=>localStorage.setItem('morokika-admin-reviews',JSON.stringify([{id:'REV-QA',name:'Salma QA',city:'Rabat',rating:5,date:'16 sept. 2026',text:'Avis temporaire utilisé uniquement par le test automatisé.',verified:false,product:'Pistache & Fleur d’Oranger',productId:'pistache-fleur-doranger',status:'À modérer'}])))
  const adminRoutes=['/admin','/admin/orders','/admin/products','/admin/custom','/admin/customers','/admin/reviews','/admin/messages','/admin/analytics','/admin/settings']
  for(const route of adminRoutes){
    await page.goto(`${baseURL}${route}`,{waitUntil:'networkidle'})
    assert.ok(await page.locator('.admin-shell').isVisible())
    assert.equal(await page.locator('meta[name="robots"]').getAttribute('content'),'noindex, nofollow')
    if(route==='/admin') await page.screenshot({path:'tests/admin-desktop.png',fullPage:true})
    await auditAccessibility(page,route)
  }

  await page.goto(`${baseURL}/admin/orders`,{waitUntil:'networkidle'})
  await page.locator('.admin-table tbody tr').first().click()
  assert.ok(await page.locator('.admin-order-drawer').isVisible())
  assert.ok(await page.locator('.admin-order-drawer').evaluate(element=>element.contains(document.activeElement)))
  await auditAccessibility(page,'/admin/orders — tiroir')
  await page.emulateMedia({media:'print'})
  assert.ok(await page.locator('.admin-sidebar').isHidden())
  assert.ok(await page.locator('.admin-order-drawer').isVisible())
  await page.emulateMedia({media:'screen'})
  await page.locator('.admin-order-drawer select').selectOption('En préparation')
  await page.getByRole('button',{name:'Terminé'}).click()
  await page.goto(`${baseURL}/admin/products`,{waitUntil:'networkidle'})
  await page.getByRole('button',{name:/Ajouter un produit/}).click()
  assert.ok(await page.locator('.admin-product-modal').evaluate(element=>element.contains(document.activeElement)))
  await auditAccessibility(page,'/admin/products — création')
  await page.getByLabel('Nom du produit').fill('Amande & Miel')
  await page.getByLabel('Description courte').fill('Amande torréfiée, miel et vanille naturelle')
  await page.locator('.admin-upload-btn input[type="file"]').first().setInputFiles('public/icon-192.png')
  await page.waitForFunction(()=>document.querySelector('.product-main-preview img')?.getAttribute('src')?.startsWith('data:image/webp'))
  await page.getByRole('button',{name:/Publier le produit/}).click()
  assert.ok(await page.getByText('Nouveau produit ajouté').isVisible())
  assert.ok(await page.getByText('Amande & Miel').first().isVisible())
  await page.getByRole('button',{name:/Augmenter le stock de Pistache/}).click()
  const caramelRow=page.locator('.admin-table tbody tr').filter({hasText:'Caramel & Dattes Majhoul'})
  for(let index=0;index<3;index++) await caramelRow.getByRole('button',{name:/Réduire le stock/}).click()
  assert.ok(await caramelRow.getByText('0',{exact:true}).isVisible())
  await page.reload({waitUntil:'networkidle'})
  assert.ok(await page.getByText('Amande & Miel').first().isVisible())
  await page.getByRole('button',{name:'Modifier Amande & Miel'}).click()
  await page.getByLabel('Prix de départ').fill('410')
  await page.getByRole('button',{name:/Enregistrer toutes les modifications/}).click()
  assert.ok(await page.getByText('Produit mis à jour',{exact:true}).isVisible())
  await page.reload({waitUntil:'networkidle'})
  const addedRow=page.locator('.admin-table tbody tr').filter({hasText:'Amande & Miel'})
  assert.ok(await addedRow.getByText('410 DH',{exact:true}).isVisible())

  await page.goto(`${baseURL}/admin/orders`,{waitUntil:'networkidle'})
  const [exportDownload]=await Promise.all([
    page.waitForEvent('download'),
    page.getByRole('button',{name:'Exporter',exact:true}).click()
  ])
  assert.equal(exportDownload.suggestedFilename(),'commandes-morokika.csv')
  await page.goto(`${baseURL}/admin/custom`,{waitUntil:'networkidle'})
  await page.locator('.kanban-column select').first().selectOption('Confirmée')
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('morokika-admin-briefs'))[0].status),'Confirmée')
  await page.getByRole('button',{name:'Ouvrir la demande SUR-260912-3194'}).click()
  assert.ok(await page.locator('.brief-drawer').evaluate(element=>element.contains(document.activeElement)))
  await auditAccessibility(page,'/admin/custom — demande')
  await page.getByLabel('Montant du devis (DH)').fill('1750')
  await page.getByLabel('Notes internes').fill('Valider les fleurs fraîches avec la cliente avant lundi.')
  await page.locator('.brief-drawer').getByRole('button',{name:'Enregistrer'}).click()
  assert.ok(await page.getByText('Devis et notes enregistrés',{exact:true}).isVisible())
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('morokika-admin-briefs')).find(brief=>brief.id==='SUR-260912-3194').quote),'1750')
  await page.goto(`${baseURL}/admin/customers`,{waitUntil:'networkidle'})
  await page.getByRole('button',{name:'Voir la fiche de Salma El Amrani'}).click()
  assert.ok(await page.locator('.customer-drawer').isVisible())
  assert.ok(await page.locator('.customer-drawer').evaluate(element=>element.contains(document.activeElement)))
  await auditAccessibility(page,'/admin/customers — fiche')
  assert.equal(await page.locator('.customer-drawer a[href^="mailto:"]').first().getAttribute('href'),'mailto:salma.e@example.ma')
  await page.locator('.customer-drawer').getByRole('button',{name:'Terminé'}).click()
  await page.goto(`${baseURL}/admin/reviews`,{waitUntil:'networkidle'})
  await page.getByRole('button',{name:/Publier/}).first().click()
  assert.ok(await page.getByText('Avis publié',{exact:true}).isVisible())
  await page.getByRole('button',{name:'Répondre'}).first().click()
  await auditAccessibility(page,'/admin/reviews — réponse')
  await page.getByLabel('Réponse publique').fill('Merci Salma, votre message fait très plaisir à toute l’équipe.')
  await page.getByRole('button',{name:'Publier la réponse'}).click()
  assert.ok(await page.getByText('Réponse publiée',{exact:true}).isVisible())
  await page.reload({waitUntil:'networkidle'})
  assert.ok(await page.getByText('Merci Salma, votre message fait très plaisir à toute l’équipe.').isVisible())
  await page.goto(`${baseURL}/admin/settings`,{waitUntil:'networkidle'})
  await page.getByLabel('Nom de la boutique').fill('MoroKika Atelier')
  await page.locator('.admin-toggle').filter({hasText:'Virement bancaire'}).click()
  await page.getByLabel('Banque').fill('Banque Test Maroc')
  await page.getByLabel('Titulaire du compte').fill('MoroKika Atelier')
  await page.getByLabel('RIB').fill('007 810 0000000000000000 00')
  await page.getByRole('button',{name:/Enregistrer tous les réglages/}).click()
  await page.reload({waitUntil:'networkidle'})
  assert.equal(await page.getByLabel('Nom de la boutique').inputValue(),'MoroKika Atelier')
  const [backupDownload]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Exporter la sauvegarde'}).click()])
  assert.match(backupDownload.suggestedFilename(),/^morokika-sauvegarde-\d{4}-\d{2}-\d{2}\.json$/)
  await page.getByLabel('Rechercher dans le tableau de bord').fill('Rose')
  await page.getByLabel('Rechercher dans le tableau de bord').press('Enter')
  await page.waitForURL('**/admin/products')
  assert.ok(await page.getByText('Rose de Marrakech').first().isVisible())
  assert.equal(await page.locator('.admin-table tbody tr').count(),1)

  await page.goto(`${baseURL}/page-inconnue`, { waitUntil:'networkidle' })
  assert.ok(await page.getByRole('heading', { name:/Cette douceur n’est plus à table/ }).isVisible())
  assert.match(await page.title(), /Page introuvable/)
  assert.equal(await page.locator('meta[name="robots"]').getAttribute('content'),'noindex, follow')
  await auditAccessibility(page,'Not found')
  await page.goto(`${baseURL}/produit/inconnu`,{waitUntil:'networkidle'})
  assert.ok(await page.getByRole('heading',{name:/Cette douceur n’est plus à table/}).isVisible())
  assert.equal(await page.locator('meta[name="robots"]').getAttribute('content'),'noindex, follow')

  await page.goto(baseURL, { waitUntil:'networkidle' })
  await page.getByRole('button', { name: 'La boutique', exact: true }).first().click()
  await page.waitForURL('**/boutique')
  assert.equal(await page.locator('.product-card').count(), 8)
  assert.equal(await page.locator('.product-card').filter({hasText:'Praliné Café Noss Noss'}).count(),0)
  const soldOutCard=page.locator('.product-card').filter({hasText:'Caramel & Dattes Majhoul'})
  assert.ok(await soldOutCard.getByRole('button',{name:'Indisponible'}).isDisabled())
  assert.ok(await page.getByText('Amande & Miel',{exact:true}).first().isVisible())
  await page.locator('.product-card').filter({hasText:'Amande & Miel'}).first().locator('.product-name').click()
  await page.waitForURL(/\/produit\/amande-miel-/)
  assert.ok(await page.getByRole('heading',{name:'Amande & Miel'}).isVisible())
  assert.ok(await page.locator('.detail-price strong').getByText('410 DH').isVisible())
  await page.goBack()
  await page.waitForURL('**/boutique')
  const pistachioCard=page.locator('.product-card').filter({hasText:'Pistache & Fleur d’Oranger'}).first()
  await pistachioCard.hover()
  await pistachioCard.getByRole('button', { name: 'Ajouter aux favoris' }).click()
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('morokika-wishlist')).length), 1)
  await page.getByRole('button', { name: /Favoris, 1 article/ }).click()
  await page.waitForURL('**/favoris')
  assert.equal(await page.locator('meta[name="robots"]').getAttribute('content'),'noindex, follow')
  assert.equal(await page.locator('.product-card').count(), 1)
  await page.goBack()
  await page.waitForURL('**/boutique')

  await page.locator('.product-card').filter({hasText:'Pistache & Fleur d’Oranger'}).first().locator('.product-name').click()
  await page.waitForURL('**/produit/**')
  assert.match(await page.title(), /MoroKika/)
  assert.equal(await page.locator('#product-schema').count(), 1)
  const productSchema=JSON.parse(await page.locator('#product-schema').textContent())
  assert.match(productSchema.image,/^https:\/\/morokika\.netlify\.app\/images\//)
  assert.match(productSchema.offers.url,/^https:\/\/morokika\.netlify\.app\/produit\//)
  await auditAccessibility(page,'Product detail')
  await page.getByRole('button', { name: /Guide des parts/ }).click()
  assert.ok(await page.getByRole('heading', { name: /Le guide des belles parts/ }).isVisible())
  await page.waitForTimeout(350)
  await auditAccessibility(page,'Size guide dialog')
  await page.locator('.size-guide').getByRole('button', { name: /8 parts/ }).click()
  assert.ok(await page.locator('.detail-price strong').getByText('450 DH').isVisible())
  await page.getByRole('button', { name: 'Écrire un avis' }).click()
  await page.waitForTimeout(350)
  await auditAccessibility(page,'Review dialog')
  await page.getByLabel('Votre prénom').fill('Nadia T.')
  await page.getByLabel('Votre avis').fill('Une création raffinée, légère et très bien présentée.')
  await page.getByRole('button', { name: /Publier mon avis/ }).click()
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('morokika-reviews')).length), 1)
  const queuedReview=await page.evaluate(()=>JSON.parse(localStorage.getItem('morokika-admin-reviews'))[0])
  assert.equal(queuedReview.status,'À modérer')
  assert.match(queuedReview.text,/création raffinée/)
  assert.ok(await page.getByText(/Une création raffinée/).isVisible())
  await page.getByRole('button', { name: /Ajouter au panier/ }).click()
  await page.locator('.cart-drawer').waitFor({ state: 'visible' })
  assert.ok(await page.locator('.cart-drawer').evaluate(element=>element.contains(document.activeElement)))
  await auditAccessibility(page,'Cart drawer')
  assert.equal(await page.locator('.cart-line').count(), 1)
  await page.getByRole('button', { name: /Passer la commande/ }).click()
  await page.waitForURL('**/checkout')
  assert.equal(await page.locator('meta[name="robots"]').getAttribute('content'),'noindex, follow')
  assert.ok(await page.getByText('Vos coordonnées').isVisible())
  await auditAccessibility(page,'Checkout')
  await page.getByLabel('Code promo').fill('BIENVENUE10')
  await page.getByRole('button', { name: 'Appliquer' }).click()
  assert.ok(await page.getByText('10 % de douceur appliqués').isVisible())
  assert.ok(await page.locator('.discount-line').isVisible())
  await page.getByLabel('Prénom').fill('Nadia')
  await page.reload({ waitUntil:'networkidle' })
  assert.equal(await page.getByLabel('Prénom').inputValue(), 'Nadia')
  assert.ok(await page.getByText('10 % de douceur appliqués').isVisible())
  await page.getByLabel('Nom', {exact:true}).fill('Test')
  await page.getByLabel('Téléphone').fill('0612345678')
  await page.getByLabel('Adresse e-mail').fill('nadia@example.ma')
  await page.getByLabel('Adresse', {exact:true}).fill('18 rue Oued Baht')
  await page.locator('label.save-check').filter({hasText:'Enregistrer mes informations pour la prochaine fois'}).click()
  await page.getByRole('button', {name:/Continuer vers la livraison/}).click()
  assert.ok(await page.getByRole('heading', {name:'Livraison'}).isVisible())
  await page.getByRole('button', {name:/Continuer vers la confirmation/}).click()
  assert.ok(await page.getByRole('heading', {name:'Confirmation'}).isVisible())
  await page.getByRole('button',{name:/Virement bancaire/}).click()
  assert.ok(await page.getByText('Banque Test Maroc',{exact:true}).isVisible())
  await page.getByRole('button',{name:/Paiement à la réception/}).click()
  await page.locator('.terms').click()
  await page.getByRole('button', {name:/Transmettre sur WhatsApp/}).click()
  assert.ok(await page.getByText(/Acceptez les conditions/).isVisible())
  await page.locator('.terms').click()
  const popupPromise=desktopContext.waitForEvent('page')
  await page.getByRole('button', {name:/Transmettre sur WhatsApp/}).click()
  const popup=await popupPromise
  assert.match(decodeURIComponent(popup.url()),/(?:wa\.me\/212708014975|phone=212708014975)/)
  await popup.close()
  assert.ok(await page.getByRole('heading', {name:/Une dernière étape/}).isVisible())
  assert.match(await page.locator('.order-success').innerText(), /#MK-\d{6}-\d{4}/)
  const savedOrder=await page.evaluate(()=>JSON.parse(localStorage.getItem('morokika-admin-orders'))[0])
  assert.equal(savedOrder.customer,'Nadia Test')
  assert.equal(savedOrder.status,'Nouvelle')
  assert.equal(savedOrder.payment,'À la réception')
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('morokika-customer')).email),'nadia@example.ma')
  await page.goto(`${baseURL}/admin/customers`,{waitUntil:'networkidle'})
  await page.locator('.admin-filters input').fill('Nadia Test')
  assert.ok(await page.getByText('Nadia Test',{exact:true}).isVisible())

  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 })
  const mobile = await mobileContext.newPage()
  await mobile.goto(baseURL, { waitUntil: 'networkidle' })
  await mobile.screenshot({ path: 'tests/home-mobile.png', fullPage: false })
  assert.ok(await mobile.getByRole('button', { name: 'Menu' }).isVisible())
  await mobile.getByRole('button', { name: 'Menu' }).click()
  assert.ok(await mobile.locator('.mobile-menu.open').isVisible())
  await auditAccessibility(mobile,'Mobile menu')
  await mobile.keyboard.press('Escape')
  assert.ok(await mobile.locator('.mobile-menu:not(.open)').isVisible())
  await mobile.context().setOffline(true)
  await mobile.waitForFunction(()=>navigator.onLine===false)
  await mobile.getByText(/Vous êtes hors ligne/).waitFor({state:'visible'})
  await mobile.context().setOffline(false)
  await mobile.goto(`${baseURL}/admin`,{waitUntil:'networkidle'})
  await mobile.screenshot({path:'tests/admin-mobile.png',fullPage:false})
  assert.ok(await mobile.getByRole('button',{name:'Ouvrir la navigation'}).isVisible())
  await mobile.getByRole('button',{name:'Ouvrir la navigation'}).click()
  assert.ok(await mobile.locator('.admin-sidebar.open').isVisible())
  await auditAccessibility(mobile,'Mobile seller navigation')

  assert.deepEqual(errors, [], `Console errors: ${errors.join('\n')}`)
  console.log('MoroKika QA passed: all storefront, content, and seller routes; open-dialog accessibility; SEO/schema/PWA assets; complete commerce; storefront-to-dashboard workflows; persistence/exports; offline state; console health; and responsive navigation.')
} finally {
  await browser?.close()
  if (server?.pid) {
    try { process.kill(-server.pid, 'SIGTERM') } catch {}
  }
}
