export const journalArticles = [
  {
    slug:'organiser-gateau-anniversaire-rabat', category:'Guide pratique', date:'13 septembre 2026', readTime:'7 min', image:'/images/collection-anniversaires.webp',
    title:'Organiser un gâteau d’anniversaire à Rabat : le guide', metaTitle:'Gâteau d’anniversaire à Rabat : le guide | MoroKika', excerpt:'Délai, nombre de parts, parfum, décor et livraison : suivez une méthode claire pour commander un gâteau d’anniversaire à Rabat sans stress.',
    intro:'Le gâteau arrive souvent à la fin d’une journée déjà riche en détails. En décidant dans le bon ordre — invités, moment, format, décor puis transport — vous obtenez une création cohérente et plus simple à servir.',
    sections:[['Commencer par la table, pas par le diamètre','Notez le nombre d’adultes et d’enfants, puis demandez-vous quand le gâteau sera servi. Après un dîner complet, une part classique suffit ; pour un goûter dont il est la pièce centrale, prévoyez deux portions supplémentaires. Chez MoroKika, les formats de 6, 8 et 12 parts répondent aux réunions courantes. Au-delà, l’atelier étudie une pièce haute, plusieurs gâteaux ou une composition sur mesure.'],['Réserver au bon moment','Pour une création de la collection, un délai de 48 heures laisse le temps de produire, refroidir et finir le gâteau dans de bonnes conditions. Une personnalisation complète demande idéalement sept jours. En période chargée, notamment les vendredis, samedis et veilles de fête, anticipez davantage : le créneau de l’atelier et celui du livreur doivent être coordonnés.'],['Donner un brief vraiment utile','Une palette de deux ou trois couleurs, une phrase sur la personne célébrée et une ou deux références visuelles sont plus utiles qu’une longue liste d’idées. Mentionnez les parfums appréciés, les éléments à éviter et les allergies dès le premier message. L’équipe peut alors proposer une direction faisable, lisible sur la table et fidèle à votre budget.'],['Préparer la réception à Rabat','Choisissez une adresse où quelqu’un pourra réceptionner le gâteau sur le créneau confirmé. Libérez une surface plane dans le réfrigérateur et gardez le gâteau dans sa boîte jusqu’au moment conseillé par l’atelier. Pour une crème légère, sortez-le généralement 15 à 25 minutes avant le service. Le retrait à Agdal reste une solution pratique si votre horaire de fête est susceptible de changer.']]
  },
  {
    slug:'gateau-mariage-maroc-guide', category:'Mariage', date:'11 septembre 2026', readTime:'8 min', image:'/images/story-table.webp',
    title:'Gâteau de mariage au Maroc : 7 questions avant le devis', metaTitle:'Gâteau de mariage au Maroc : préparer le devis | MoroKika', excerpt:'Invités, lieu, saison, décor et service : préparez les informations qui rendent un devis vraiment précis.',
    intro:'Un gâteau de mariage n’est pas seulement une image à reproduire. Il doit offrir le bon nombre de parts, rester stable jusqu’au service et dialoguer avec le lieu. Un premier échange précis évite les estimations vagues et accélère la proposition.',
    sections:[['Quelle est la date et où aura lieu la réception ?','La date détermine la disponibilité de l’atelier ; le lieu révèle les contraintes de livraison, d’accès et de conservation. Indiquez la ville, l’horaire attendu, l’étage éventuel, la présence d’un ascenseur et l’existence d’une chambre froide. Pour Rabat, Salé et Témara, une livraison peut être étudiée selon le format. Une pièce montée exige parfois une installation sur place plutôt qu’une simple remise.'],['Combien de parts faut-il réellement ?','Communiquez le nombre d’invités confirmé, le type de menu et la place du gâteau parmi les desserts. Si une table de pâtisseries marocaines est déjà prévue, toutes les personnes ne prendront pas une grande part. L’atelier peut distinguer le volume décoratif du nombre de portions grâce à une composition à étages adaptée, sans surdimensionner inutilement la recette.'],['Quel univers visuel et quelles saveurs ?','Rassemblez la palette, les fleurs, le faire-part et quelques images d’ambiance plutôt qu’une photo unique à copier. Précisez aussi vos préférences aromatiques : chocolat, praliné, agrumes, pistache ou fleur d’oranger. Une dégustation permet ensuite de vérifier l’équilibre entre biscuit, crème et insert. Les fleurs naturelles doivent être validées pour un usage alimentaire ou isolées correctement.'],['Quel budget et quel niveau de service ?','Le prix dépend des parts, de la structure, du temps de décor, des éléments façonnés, des fleurs et de la logistique. Donnez une fourchette honnête dès le départ : elle aide à arbitrer entre hauteur, complexité et finition. Demandez enfin ce que comprend le devis — livraison, installation, support, consigne éventuelle et horaire d’intervention — pour comparer des propositions réellement équivalentes.']]
  },
  {
    slug:'transport-conservation-gateau', category:'Conseils', date:'4 septembre 2026', readTime:'6 min', image:'/images/signature-box.webp',
    title:'Transport et conservation d’un gâteau : les bons gestes', metaTitle:'Transport et conservation des gâteaux | MoroKika', excerpt:'Du réfrigérateur à la table, découvrez les bons gestes de transport et de conservation pour préserver la tenue, les textures et les parfums du gâteau.',
    intro:'Un gâteau fini réunit des textures sensibles à la chaleur, aux mouvements et aux odeurs. Quelques gestes simples suffisent à protéger le travail de l’atelier jusqu’à la première part.',
    sections:[['Pendant le transport : rester à plat','La boîte doit reposer sur une surface horizontale, idéalement le plancher climatisé de la voiture plutôt qu’un siège incliné. Évitez le coffre chaud, les freinages brusques et l’exposition au soleil. Ne posez rien sur l’écrin. Pour les grands formats et les pièces à étages, privilégiez la livraison organisée par l’atelier : le véhicule, les tapis antidérapants et l’itinéraire sont adaptés au produit.'],['Au réfrigérateur : protéger sans comprimer','Dégagez une tablette avant l’arrivée du gâteau et conservez-le dans sa boîte. Elle protège la finition, limite les odeurs et évite la condensation directe. Ne placez pas le gâteau près d’aliments très parfumés ni contre la paroi humide. Les conditions varient selon la recette : suivez toujours l’indication remise avec votre commande et contactez l’atelier en cas de doute.'],['Avant le service : retrouver les textures','Un entremets servi trop froid masque ses arômes et raffermit excessivement les crèmes. Selon sa composition et la température de la pièce, une sortie 15 à 25 minutes avant la découpe est souvent adaptée. Retirez la boîte dans un endroit frais, loin d’une fenêtre ensoleillée. En été, réduisez ce temps et ne laissez pas le gâteau attendre sur une table extérieure.'],['Après la fête : conserver les parts restantes','Replacez rapidement les parts dans une boîte hermétique au réfrigérateur et consommez-les selon le délai indiqué par l’atelier. Utilisez un couteau propre à chaque découpe et ne recongelez jamais un gâteau qui a déjà décongelé. Pour offrir une part à un invité, emballez-la juste avant son départ et recommandez un trajet direct vers un réfrigérateur.']]
  },
  {
    slug:'pistache-du-maroc', category:'Ingrédients', date:'08 septembre 2026', readTime:'4 min', image:'/images/story-ingredients.webp',
    title:'La pistache, ce petit trésor vert', excerpt:'Choix, torréfaction, conservation et textures : les repères qui permettent de préserver le parfum et la couleur naturelle de la pistache.',
    intro:'Chez MoroKika, la pistache n’est jamais un simple décor. Elle structure la dégustation, apporte du relief et fait le lien entre douceur, végétal et gourmandise.',
    sections:[['Choisir le fruit juste','Une pistache adaptée à la pâtisserie présente un parfum net, une texture pleine et une couleur naturellement nuancée. Sa fraîcheur compte davantage qu’une teinte artificiellement uniforme ; l’odeur et le goût permettent aussi de repérer un fruit rance ou fatigué.'],['Une torréfaction douce','Quelques minutes de chaleur suffisent à révéler les notes grillées du fruit. Une torréfaction trop poussée apporte de l’amertume et masque la nuance végétale ; la durée doit être adaptée à la taille, à l’humidité et à l’usage prévu.'],['De la texture à chaque étage','Pâte pure dans la crème, praliné croustillant au cœur, éclats fins sur le glaçage : plusieurs expressions d’un même ingrédient créent une bouchée plus longue et plus nuancée.'],['Conserver la pistache avant de la travailler','La lumière, la chaleur et l’air accélèrent l’oxydation des fruits secs. Un contenant fermé, placé à l’abri de la lumière et de la chaleur, ralentit cette dégradation. Une pistache fatiguée perd sa note végétale et développe parfois une amertume que le sucre ne doit pas masquer.'],['Pistache et information allergène','La pistache appartient à la famille des fruits à coque et doit être signalée clairement. Même lorsqu’une autre recette n’en contient pas dans sa formulation, l’atelier partagé ne permet pas de garantir l’absence totale de traces croisées. Une allergie sévère doit toujours être communiquée avant la commande.']]
  },
  {
    slug:'choisir-taille-gateau', category:'Conseils', date:'29 août 2026', readTime:'3 min', image:'/images/story-table.webp',
    title:'Quelle taille de gâteau choisir ?', excerpt:'Six, huit ou douze parts : utilisez nos repères de formats, de menu et de découpe pour servir chaque invité généreusement sans gaspiller.',
    intro:'Le bon format dépend du nombre d’invités, mais aussi du moment du service et du reste du menu. Voici les repères utilisés dans notre atelier.',
    sections:[['Pour 4 à 6 personnes','Notre format 16 cm offre six parts généreuses. Il convient à un dîner intime, un goûter ou une petite attention à partager.'],['Pour 7 à 9 personnes','Le format 20 cm est le plus polyvalent. Ses huit parts accompagnent facilement un anniversaire familial ou un déjeuner du dimanche.'],['Pour 10 à 14 personnes','Le format 24 cm permet douze belles portions. Au-delà, notre service sur mesure adapte le diamètre, la hauteur et la structure à votre réception.'],['Tenir compte du reste du menu','Après un repas complet ou à côté de plusieurs pâtisseries, une part standard par personne suffit souvent. Pour un goûter où le gâteau tient le premier rôle, prévoyez une ou deux portions de marge. Les enfants peuvent prendre de plus petites parts, mais il vaut mieux ne pas réduire le format uniquement sur cette hypothèse.'],['Préparer une découpe régulière','Utilisez un couteau long, propre et légèrement tiédi, puis essuyez-le entre les parts. Commencez par marquer les portions avant de couper complètement. Une découpe régulière évite de servir de très grandes parts au début et de manquer de gâteau pour les derniers invités.']]
  },
  {
    slug:'fleur-oranger-autrement', category:'Savoir-faire', date:'17 août 2026', readTime:'5 min', image:'/images/story-atelier.webp',
    title:'La fleur d’oranger, autrement', excerpt:'Infusion, dosage et associations : les gestes qui transforment un parfum familier en signature contemporaine.',
    intro:'Son parfum appartient à la mémoire de nombreuses tables marocaines. Notre travail consiste à le respecter tout en lui donnant une expression plus légère et précise.',
    sections:[['La qualité avant la quantité','Une eau de fleur d’oranger au parfum net permet un dosage très fin. Dans une préparation sensible, un ajout à température modérée aide à préserver les notes les plus délicates ; la quantité doit toujours être ajustée au produit utilisé.'],['Créer un équilibre','La pistache, les agrumes et la vanille lui offrent des contrepoints naturels. L’acidité évite toute lourdeur tandis qu’une crème peu sucrée prolonge le parfum sans le saturer.'],['Un souvenir dans chaque part','Le goût contemporain ne signifie pas oublier les recettes familiales. Il s’agit plutôt de retrouver leur émotion avec des textures nouvelles et une finition plus nette.'],['Infuser sans rendre le parfum savonneux','La fleur d’oranger devient envahissante lorsque le dosage cherche à compenser une matière première peu expressive. Il vaut mieux construire le parfum par petites touches, goûter après le repos et l’associer à une base lactée, un agrume ou un fruit sec qui lui donne du relief.'],['La servir avec la bonne boisson','Un thé vert léger, une verveine ou un café peu sucré accompagnent mieux ce parfum qu’une boisson très aromatisée. La température compte aussi : une crème trop froide masque les notes florales. Sortez le gâteau selon l’indication de la recette afin de retrouver une dégustation plus précise.']]
  },
  {
    slug:'choisir-parfum-gateau', category:'Saveurs', date:'12 août 2026', readTime:'8 min', image:'/images/story-ingredients.webp',
    title:'Quel parfum de gâteau choisir pour faire plaisir à toute la table ?', metaTitle:'Quel parfum de gâteau choisir ? | Guide MoroKika', excerpt:'Chocolat, fruits, pistache ou fleur d’oranger : choisissez selon le repas, la saison et vos invités.',
    intro:'Le meilleur parfum n’est pas forcément le plus spectaculaire. Il doit correspondre au moment, rester agréable après le menu et offrir assez de repères familiers pour que chaque invité ait envie d’une part.',
    sections:[['Partir du moment de dégustation','Après un déjeuner généreux, privilégiez une composition fraîche, acidulée ou florale : agrumes, fruits rouges, figue et crèmes légères laissent une impression nette. Pour un goûter ou une pause d’équipe, le chocolat, le café et le praliné apportent davantage de profondeur. Le soir, tenez aussi compte des boissons prévues et de la température de la pièce.'],['Trouver le bon niveau d’intensité','Un groupe aux goûts variés apprécie souvent une base connue accompagnée d’une note plus personnelle. Le chocolat noir devient plus accessible avec une noisette pralinée ; la vanille gagne du relief avec la figue et le thym ; la pistache reste lisible lorsqu’elle est éclairée par la fleur d’oranger. Évitez d’empiler trop d’arômes : trois axes bien équilibrés valent mieux qu’une liste difficile à distinguer.'],['Faire une place aux saveurs marocaines','Fleur d’oranger, datte Majhoul, sésame, safran, agrumes et café peuvent évoquer le Maroc sans transformer le gâteau en dessert excessivement sucré. Le rôle de la pâtisserie contemporaine est de travailler les dosages, l’acidité et les textures pour laisser chaque ingrédient s’exprimer. Si un parfum porte une mémoire particulière pour votre famille, mentionnez-la dans le brief.'],['Ne jamais oublier allergies et préférences','Demandez en amont si des invités évitent les fruits à coque, le sésame, le gluten, les œufs ou le lait. Une recette peut être formulée sans un ingrédient précis sans pour autant convenir à une allergie sévère, car l’atelier partagé expose à des traces croisées. Communiquez les besoins clairement et conservez l’information jusqu’au service.']]
  },
  {
    slug:'brief-gateau-personnalise', category:'Sur mesure', date:'6 août 2026', readTime:'7 min', image:'/images/atelier-detail.webp',
    title:'Comment rédiger un bon brief de gâteau personnalisé ?', metaTitle:'Brief de gâteau personnalisé : les informations utiles | MoroKika', excerpt:'Date, nombre de parts, saveurs, couleurs, références et budget : rassemblez les informations qui permettent à l’atelier de répondre précisément.',
    intro:'Un bon brief ne cherche pas à dessiner le gâteau à la place du pâtissier. Il rassemble les contraintes, les préférences et l’atmosphère recherchée afin de transformer une première idée en proposition réalisable.',
    sections:[['Les cinq informations indispensables','Commencez par la date, la ville, le nombre de personnes, le type d’occasion et le moment du service. Ces éléments déterminent la disponibilité, le format et la logistique avant même de parler du décor. Ajoutez un numéro joignable et précisez si vous préférez un retrait à Agdal ou une livraison. Une date encore flexible doit être signalée comme telle.'],['Des références visuelles, pas une copie','Deux ou trois images suffisent pour montrer une palette, une texture ou une silhouette. Expliquez ce que vous aimez dans chacune : la hauteur, le mouvement des fleurs, le contraste ou la sobriété. Évitez de demander la reproduction exacte du travail d’un autre atelier. MoroKika traduit vos références dans son propre langage et selon les contraintes de tenue du gâteau.'],['Parfums, allergies et éléments à éviter','Listez les saveurs appréciées et celles que la personne célébrée n’aime pas. Indiquez les allergies dès le premier message, y compris pour les invités, et gardez en tête que des traces croisées restent possibles dans un atelier qui manipule plusieurs allergènes. Si le menu est déjà connu, partagez-le : il aide à choisir une finale fraîche ou plus gourmande.'],['Une fourchette de budget fait gagner du temps','Le prix dépend des parts, de la structure, du temps de décor et du transport. Donner une fourchette ne réduit pas la créativité ; cela permet de concentrer la proposition sur les arbitrages utiles. Avant validation, relisez ensemble l’orthographe du message, le format, le parfum, la date, le lieu, le créneau et les conditions de conservation.']]
  },
  {
    slug:'message-gateau-anniversaire', category:'Inspiration', date:'29 juillet 2026', readTime:'6 min', image:'/images/rose-raspberry.webp',
    title:'Quel message écrire sur un gâteau d’anniversaire ?', metaTitle:'Messages pour gâteau d’anniversaire : idées | MoroKika', excerpt:'Des idées courtes, tendres ou joyeuses en français, en darija et en arabe, avec les règles de lisibilité.',
    intro:'Quelques mots suffisent à transformer un gâteau en attention personnelle. La bonne formule tient compte de la place disponible, du ton de la fête et surtout de l’orthographe que vous souhaitez voir apparaître.',
    sections:[['Pourquoi les messages courts fonctionnent mieux','Sur un gâteau de 16 ou 20 cm, une formule de deux à cinq mots reste plus nette et laisse respirer le décor. « Joyeux anniversaire Lina », « 30 ans de lumière », « Notre étoile » ou simplement un prénom et une date sont faciles à lire sur les photos. Pour une phrase plus longue, utilisez plutôt la carte glissée dans l’écrin.'],['Des idées chaleureuses en français','Pour une famille : « Que du bonheur », « Notre fierté » ou « Une année de plus à t’aimer ». Pour un ami : « À ta plus belle année », « Toujours plus haut » ou une expression comprise seulement par votre groupe. Au travail : « Bravo pour cette étape », « Merci pour tout » ou « Belle continuation » gardent un ton juste et professionnel.'],['Une formule en darija ou en arabe','Vous pouvez choisir une translittération familière comme « Sana hilwa » ou une inscription en arabe telle que « عيد ميلاد سعيد », qui signifie joyeux anniversaire. Pour souhaiter une longue vie, certaines familles utilisent « لعقوبة لمية سنة ». Envoyez toujours le texte exact à copier, déjà validé par la famille, car l’atelier ne doit pas deviner une orthographe ou une formulation régionale.'],['Les détails à confirmer avant la finition','Écrivez le prénom avec les accents, traits d’union et majuscules souhaités. Vérifiez l’âge, surtout si le gâteau est une surprise, puis précisez la langue et le sens de lecture. L’atelier confirme la faisabilité selon le diamètre et le décor. Un texte alimentaire doit rester sobre : une inscription trop dense devient fragile et moins élégante.']]
  },
  {
    slug:'organiser-gateau-sbaa', category:'Célébrations', date:'20 juillet 2026', readTime:'7 min', image:'/images/vanilla-fig.webp',
    title:'Organiser le gâteau d’un sbâa : parts, parfum et timing', metaTitle:'Gâteau de sbâa : parts, parfum et organisation | MoroKika', excerpt:'Un guide pratique pour choisir le format, le décor et la livraison pendant les premiers jours du bébé.',
    intro:'Le sbâa se prépare alors que le rythme de la famille vient de changer. Une organisation simple, un interlocuteur unique et quelques décisions prises dans le bon ordre permettent de garder toute l’attention pour la rencontre.',
    sections:[['Nommer une personne de contact','La personne qui commande n’est pas toujours disponible le jour de la réception. Désignez un proche capable de valider le message, répondre au livreur et libérer une place au réfrigérateur. Transmettez son téléphone avec l’adresse complète et le créneau. Cette petite précaution évite de solliciter les parents au mauvais moment.'],['Calculer les parts avec le reste de la table','Comptez les adultes, les enfants et les autres desserts. Si le gâteau accompagne du thé et plusieurs pâtisseries, une part modérée par personne est généralement suffisante. Pour un goûter plus simple, gardez deux portions de marge. Au-delà de douze parts, demandez si un grand format ou plusieurs gâteaux faciliteront le transport et la découpe.'],['Choisir un décor qui traverse les photos','Les palettes ivoire, sable, sauge, rose poudré ou bleu grisé vieillissent bien et s’accordent facilement à une table familiale. Un prénom, une date ou une formule courte personnalise le gâteau sans le surcharger. Si des fleurs ou accessoires sont prévus autour, communiquez-les afin que l’ensemble reste cohérent et sûr au contact alimentaire.'],['Anticiper la conservation','Dégagez une tablette stable au réfrigérateur avant l’arrivée. Gardez le gâteau dans son écrin et suivez l’indication de sortie donnée pour la recette, souvent 15 à 25 minutes avant le service. Ne le laissez pas attendre près d’une fenêtre ou dans une pièce chaude, particulièrement lorsqu’il contient une mousse ou une crème légère.']]
  },
  {
    slug:'gateau-evenement-entreprise', category:'Vie d’équipe', date:'11 juillet 2026', readTime:'7 min', image:'/images/story-table.webp',
    title:'Choisir un gâteau pour un événement d’entreprise à Rabat', metaTitle:'Gâteau d’entreprise à Rabat : guide | MoroKika', excerpt:'Effectif, horaire, message et accès au bureau : les décisions qui simplifient une commande professionnelle.',
    intro:'Une attention partagée au bureau doit arriver à l’heure, être simple à servir et correspondre au ton de l’événement. Le bon choix commence donc par l’usage et la logistique, avant la couleur du décor.',
    sections:[['Adapter le format au type d’événement','Pour un anniversaire d’équipe ou un pot de départ, comptez les personnes réellement présentes et le moment de service. Une réunion à 10 heures appelle des parts différentes d’un dessert après déjeuner. Si plusieurs services ou étages sont concernés, demandez si deux formats plus faciles à déplacer seraient préférables à une grande pièce.'],['Choisir un message professionnel mais humain','« Merci pour cette aventure », « Bravo l’équipe », une date de lancement ou le prénom d’un collègue suffisent souvent. Une palette inspirée de la marque peut guider la finition sans transformer le gâteau en support publicitaire. Partagez uniquement les éléments dont l’usage a été validé et laissez l’atelier proposer une interprétation sobre.'],['Préparer la livraison au bureau','Indiquez le bâtiment, l’étage, l’accès au parking, l’accueil à prévenir et le nom d’un contact disponible. Vérifiez qu’un réfrigérateur assez large est accessible : les réfrigérateurs de bureau sont souvent encombrés ou trop étroits. Prévoyez aussi un couteau long, une pelle, des assiettes et des serviettes avant le début de la réunion.'],['Commander dans le bon délai','Quarante-huit heures sont conseillées pour un gâteau de la collection ; un décor adapté à votre événement demande au moins sept jours. Pour une date fixe réunissant beaucoup de personnes, contactez l’atelier dès que l’effectif est connu. Le devis ou le récapitulatif doit confirmer le format, le parfum, le message, l’adresse et le créneau.']]
  },
  {
    slug:'accord-the-gateau-marocain', category:'Art de recevoir', date:'2 juillet 2026', readTime:'7 min', image:'/images/pistachio-blossom.webp',
    title:'Quel thé servir avec un gâteau aux saveurs marocaines ?', metaTitle:'Accords thé et gâteau marocain | Conseils MoroKika', excerpt:'Thé vert, menthe, verveine ou café : composez un accord qui accompagne le gâteau sans masquer ses parfums.',
    intro:'La boisson peut alléger une crème, prolonger une épice ou au contraire saturer le palais. Pour créer un accord harmonieux, observez l’intensité, le sucre et la température plutôt que de chercher une règle unique.',
    sections:[['Pistache et fleur d’oranger','Un thé vert peu amer, servi avec une menthe fraîche modérée, soutient la pistache et nettoie la texture de la crème. Évitez une infusion trop longue ou très sucrée : elle couvrirait la fleur d’oranger. Une verveine légère fonctionne également lorsque vous souhaitez un service sans caféine en fin de soirée.'],['Chocolat, noisette et café','Le chocolat noir accepte une boisson plus structurée. Un café noss noss peu sucré rappelle le praliné et adoucit l’amertume ; un thé noir léger crée davantage de contraste. Servez de petites tasses et de l’eau à côté, surtout après un repas. La boisson doit rester légèrement moins sucrée que le gâteau.'],['Agrumes, safran et fruits rouges','Les agrumes apprécient un thé vert clair ou une infusion de verveine, dont les notes citronnées prolongent la fraîcheur. Avec framboise et rose, choisissez une infusion florale très discrète pour ne pas doubler le parfum. Le safran gagne à être accompagné simplement : une boisson trop épicée rendrait l’ensemble confus.'],['La température et le rythme du service','Un thé brûlant servi avec un entremets très froid empêche de percevoir les nuances. Sortez le gâteau selon les conseils de l’atelier et laissez le thé redescendre légèrement avant de servir. Présentez d’abord une petite part ; les invités peuvent se resservir tout en gardant les textures fraîches.']]
  }
]

export const articlePublishedDates = {
  'organiser-gateau-anniversaire-rabat':'2026-09-13',
  'gateau-mariage-maroc-guide':'2026-09-11',
  'pistache-du-maroc':'2026-09-08',
  'transport-conservation-gateau':'2026-09-04',
  'choisir-taille-gateau':'2026-08-29',
  'fleur-oranger-autrement':'2026-08-17',
  'choisir-parfum-gateau':'2026-08-12',
  'brief-gateau-personnalise':'2026-08-06',
  'message-gateau-anniversaire':'2026-07-29',
  'organiser-gateau-sbaa':'2026-07-20',
  'gateau-evenement-entreprise':'2026-07-11',
  'accord-the-gateau-marocain':'2026-07-02'
}

export const seoLandingPages = [
  {
    path:'/gateaux-rabat',metaTitle:'Pâtisserie artisanale et gâteaux à Rabat | MoroKika',metaDescription:'Commandez un gâteau artisanal à Rabat : créations signature, anniversaires et formats sur mesure, préparés à Agdal avec livraison réfrigérée.',region:'Rabat',service:'Pâtisserie artisanale et livraison de gâteaux',eyebrow:'Pâtisserie artisanale · Rabat',title:'Des gâteaux à Rabat, façonnés pour les moments qui comptent.',intro:'MoroKika imagine à Agdal des gâteaux fins, peu sucrés et préparés à la commande. Pistache, fleur d’oranger, datte Majhoul, agrumes et chocolat composent une collection pensée pour les anniversaires, cadeaux et grandes tablées à Rabat.',image:'/images/story-atelier.webp',imageAlt:'Préparation artisanale d’un gâteau dans l’atelier MoroKika à Rabat',facts:[['Atelier','Agdal, Rabat'],['Préparation','À la commande'],['Livraison','Rabat et environs']],
    sections:[
      ['Une pâtisserie contemporaine ancrée à Rabat','Notre atelier réunit le geste pâtissier classique et des saveurs familières au Maroc. Chaque biscuit, crème, praliné et décor est préparé avec précision pour obtenir des textures nettes et une douceur équilibrée. Les gâteaux quittent l’atelier dans un écrin adapté au transport réfrigéré.'],
      ['Choisir le bon gâteau pour votre occasion','La collection permanente convient aux anniversaires, déjeuners, cadeaux et visites familiales. Les formats de 6, 8 et 12 parts permettent de servir une petite table comme une réception plus généreuse. Pour quinze personnes ou davantage, une forme particulière ou un décor entièrement personnalisé, notre service sur mesure construit une proposition dédiée.'],
      ['Livraison de gâteau à Rabat ou retrait à Agdal','Nous livrons à Rabat sur un créneau choisi au checkout et proposons aussi le retrait gratuit à l’atelier. Agdal, Hassan, Hay Riad, Souissi, Océan et les autres quartiers sont desservis selon les créneaux disponibles. La date affichée sur chaque fiche produit reste la meilleure indication pour organiser votre dégustation sans stress.']
    ],highlights:['Formats de 6, 8 et 12 parts','Livraison offerte dès 450 DH','Retrait gratuit à Agdal'],productIds:['pistache-fleur-doranger','atlas-chocolat','rose-framboise'],
    faqs:[['Quel délai prévoir pour un gâteau à Rabat ?','Prévoyez idéalement 48 heures pour une création de la collection et au moins sept jours pour un projet sur mesure.'],['Livrez-vous dans tous les quartiers de Rabat ?','Nous desservons Rabat selon les créneaux disponibles. L’adresse saisie au checkout permet de confirmer la livraison et son tarif.'],['Puis-je retirer mon gâteau à l’atelier ?','Oui. Le retrait à notre atelier d’Agdal est gratuit, sur le créneau confirmé lors de la commande.'],['Quels sont les prix des gâteaux MoroKika ?','Les créations de la collection commencent à 320 DH. Le prix évolue selon la recette, le format et le niveau de personnalisation.']],related:['/gateau-anniversaire-rabat','/gateau-sur-mesure-rabat','/livraison-gateau-sale'],ctaTitle:'Une table à préparer à Rabat ?',ctaText:'Choisissez une création de la collection ou racontez-nous votre projet personnalisé.'
  },
  {
    path:'/gateau-anniversaire-rabat',metaTitle:'Gâteau d’anniversaire à Rabat, livré à domicile | MoroKika',metaDescription:'Trouvez votre gâteau d’anniversaire à Rabat : 6, 8 ou 12 parts, message offert, recettes artisanales et livraison réfrigérée.',region:'Rabat',service:'Gâteaux d’anniversaire',eyebrow:'Anniversaires · Rabat',title:'Un gâteau d’anniversaire à Rabat, aussi délicat que votre attention.',intro:'Un anniversaire mérite un gâteau qui rassemble sans alourdir la fin du repas. MoroKika prépare à Rabat des créations élégantes, aux parfums équilibrés, disponibles en plusieurs formats et livrées avec soin.',image:'/images/story-table.webp',imageAlt:'Gâteau d’anniversaire élégant dressé sur une table à Rabat',facts:[['Formats','6, 8 ou 12 parts'],['Petit mot','Personnalisé et offert'],['Délai conseillé','48 heures']],
    sections:[
      ['Quel format choisir pour un anniversaire ?','Pour quatre à six convives, le format 16 cm offre six parts généreuses. Le 20 cm convient à sept à neuf personnes, tandis que le 24 cm accompagne une table de dix à quatorze invités. Notre guide des tailles détaille ces repères et le service sur mesure prend le relais pour les groupes plus importants.'],
      ['Des saveurs pour les adultes comme pour les familles','Pistache et fleur d’oranger apporte une note marocaine délicate. Atlas Chocolat Noir séduit les amateurs de saveurs intenses, tandis que Rose de Marrakech et Safran & Agrumes offrent une finale plus fraîche. Chaque fiche indique les ingrédients principaux et les allergènes à connaître avant de commander.'],
      ['Livraison le jour choisi à Rabat','Sélectionnez votre date et votre créneau pendant la commande. Le gâteau est protégé dans son écrin puis transporté au frais jusqu’à votre adresse à Rabat. Un message de quarante caractères peut être ajouté gratuitement pour signer votre attention.']
    ],highlights:['Message d’anniversaire offert','Conservation et transport au frais','Conseil sur le nombre de parts'],productIds:['rose-framboise','pistache-fleur-doranger','atlas-chocolat'],
    faqs:[['Combien coûte un gâteau d’anniversaire à Rabat ?','Les créations commencent à 320 DH pour six parts. Les formats supérieurs et les décors sur mesure font évoluer le prix.'],['Puis-je écrire un message sur le gâteau ?','Oui. Un petit mot de quarante caractères peut être ajouté gratuitement depuis la fiche produit.'],['Peut-on commander pour plus de quinze personnes ?','Oui. Utilisez le formulaire sur mesure afin que l’atelier adapte le diamètre, la hauteur et la décoration.'],['Comment conserver le gâteau avant la fête ?','Conservez-le entre 2 °C et 5 °C, puis sortez-le environ vingt minutes avant de servir.']],related:['/gateaux-rabat','/gateau-sur-mesure-rabat','/gateau-mariage-rabat'],ctaTitle:'L’anniversaire approche ?',ctaText:'Choisissez le parfum, le nombre de parts et votre créneau de livraison à Rabat.'
  },
  {
    path:'/gateau-sur-mesure-rabat',metaTitle:'Gâteau sur mesure à Rabat — Cake design artisanal | MoroKika',metaDescription:'Imaginez un gâteau sur mesure à Rabat pour anniversaire, fiançailles, sbâa ou événement. Brief en ligne, étude de faisabilité et proposition selon les informations transmises.',region:'Rabat',service:'Création de gâteaux sur mesure',eyebrow:'Créations personnalisées · Rabat',title:'Votre gâteau sur mesure à Rabat commence par une histoire.',intro:'Une couleur, une fleur, une saveur d’enfance ou une table entière à célébrer : notre atelier transforme votre idée en gâteau personnalisé. Le brief en ligne nous aide à comprendre l’occasion, le nombre d’invités, l’univers visuel et votre budget.',image:'/images/atelier-detail.webp',imageAlt:'Décoration à la main d’un gâteau sur mesure dans un atelier de Rabat',facts:[['Réponse','Après étude du brief'],['Réservation','7 jours conseillés'],['Projet','Sans engagement']],
    sections:[
      ['Un brief simple pour cadrer votre création','Commencez par indiquer l’occasion et le nombre d’invités. Choisissez ensuite une famille de saveurs, un style visuel et un budget indicatif. Vous pouvez décrire les couleurs, l’inscription ou l’inspiration souhaitée ; l’atelier affinera avec vous les détails réalisables.'],
      ['Anniversaire, fiançailles, mariage, sbâa ou événement professionnel','Nous adaptons le format et la finition aux moments familiaux comme aux réceptions de marque. Une création sur mesure peut reprendre une palette, un motif, un monogramme ou une ambiance, tout en préservant la lisibilité et l’élégance propres à MoroKika.'],
      ['Du devis à la remise du gâteau','Après étude du brief, vous recevez une proposition détaillant le format, les saveurs, le décor et le budget. La date est confirmée selon la capacité de l’atelier. La livraison réfrigérée dessert Rabat, Salé, Témara, Kénitra et Casablanca ; le retrait à Agdal reste possible.']
    ],highlights:['Devis personnalisé','Recette et décor coordonnés','Suivi direct avec l’atelier'],productIds:['pistache-fleur-doranger','rose-framboise','safran-agrumes'],
    faqs:[['Quel délai faut-il pour un gâteau personnalisé à Rabat ?','Prévoyez au moins sept jours. Pour un mariage ou une réception importante, contactez-nous le plus tôt possible.'],['Le devis est-il payant ?','Non. La demande initiale est sans engagement et permet à l’atelier de préparer une proposition adaptée.'],['Puis-je envoyer une idée précise de décoration ?','Oui. Décrivez votre inspiration dans le brief ; l’équipe vous indiquera comment l’adapter à notre style et aux contraintes pâtissières.'],['Réalisez-vous des gâteaux sans fruits à coque ?','Nous pouvons étudier une recette formulée sans fruits à coque, mais l’atelier en manipule et ne peut garantir l’absence de traces croisées.']],related:['/gateaux-rabat','/gateau-anniversaire-rabat','/gateau-mariage-rabat'],ctaTitle:'Prêt à raconter votre occasion ?',ctaText:'Complétez le brief : notre atelier vous répond avec une première proposition.'
  },
  {
    path:'/gateau-mariage-rabat',metaTitle:'Gâteau de mariage et fiançailles à Rabat | MoroKika',metaDescription:'Gâteau de mariage ou de fiançailles à Rabat : création élégante, saveurs personnalisées, devis et livraison coordonnée avec votre réception.',region:'Rabat-Salé',service:'Gâteaux de mariage et de fiançailles',eyebrow:'Mariages & fiançailles · Rabat',title:'Un gâteau de mariage à Rabat, pensé comme le dernier geste de la réception.',intro:'Pour un mariage ou des fiançailles, le gâteau doit être beau à l’arrivée et juste à la dégustation. MoroKika compose des pièces sobres et contemporaines, accordées à votre nombre d’invités, à votre palette et au rythme de la réception.',image:'/images/signature-box.webp',imageAlt:'Présentation raffinée d’une création MoroKika pour mariage à Rabat',facts:[['Occasions','Mariage & fiançailles'],['Dimensionnement','Selon vos invités'],['Zone','Rabat, Salé et Témara']],
    sections:[
      ['Dimensionner la pièce selon la réception','Le nombre de convives, l’horaire du dessert et la présence d’autres douceurs déterminent le format. L’atelier vous aide à prévoir des parts généreuses sans excès et à choisir entre un grand gâteau, plusieurs niveaux ou une composition de formats coordonnés.'],
      ['Créer un accord entre décor et saveurs','Ivoire texturé, fleurs fraîches autorisées au contact alimentaire, touches dorées, agrumes, pistache, vanille ou chocolat : chaque choix sert l’ensemble. Nous recherchons une silhouette élégante et des saveurs qui restent fraîches après un repas de fête.'],
      ['Anticiper la livraison à Rabat et dans les environs','Une grande création demande une coordination précise avec le lieu de réception. Communiquez l’adresse, l’horaire de service et les contraintes d’accès dès le brief. Nous confirmons ensuite le créneau et les conditions de transport réfrigéré vers Rabat, Salé ou Témara.']
    ],highlights:['Format calculé par convive','Décor coordonné à votre réception','Transport réfrigéré planifié'],productIds:['pistache-fleur-doranger','vanille-figue','rose-framboise'],
    faqs:[['Quand réserver un gâteau de mariage à Rabat ?','Contactez l’atelier plusieurs semaines à l’avance, surtout pour les week-ends et les grandes réceptions.'],['Pouvez-vous assortir le gâteau à notre décoration ?','Oui. Indiquez votre palette, les matières et les fleurs prévues afin de construire une finition cohérente.'],['Comment calculez-vous le nombre de parts ?','Nous tenons compte du nombre d’invités, du moment de service et des autres desserts présents sur la table.'],['Livrez-vous les lieux de réception autour de Rabat ?','La livraison peut être organisée à Rabat, Salé et Témara selon la date, le format et les conditions d’accès.']],related:['/gateau-sur-mesure-rabat','/gateau-anniversaire-rabat','/livraison-gateau-sale'],ctaTitle:'Préparons votre table de fête.',ctaText:'Partagez la date, le nombre d’invités et l’univers de votre réception.'
  },
  {
    path:'/livraison-gateau-sale',metaTitle:'Livraison de gâteau à Salé — Commande en ligne | MoroKika',metaDescription:'Faites livrer un gâteau artisanal à Salé : commande en ligne, transport réfrigéré, créneaux planifiés et tarif clair de 35 DH.',region:'Salé',service:'Livraison de gâteaux',eyebrow:'Livraison de gâteaux · Salé',title:'Votre gâteau livré à Salé, frais et prêt à partager.',intro:'Depuis notre atelier voisin d’Agdal, nous préparons chaque gâteau à la commande puis organisons sa livraison à Salé dans un conditionnement adapté. La collection couvre les anniversaires, cadeaux, déjeuners et attentions de dernière ligne droite.',image:'/images/hero-cake.webp',imageAlt:'Gâteau artisanal MoroKika préparé pour une livraison à Salé',facts:[['Tarif standard','35 DH'],['Délai conseillé','48 h conseillées'],['Retrait atelier','Sur créneau confirmé']],
    sections:[
      ['Commander un gâteau en ligne pour Salé','Choisissez votre création, le format et le petit mot depuis la boutique. Le checkout confirme la ville, l’adresse, la date et le créneau. Les tarifs sont calculés avant le paiement : la livraison standard à Salé est de 35 DH. Le montant final reste visible avant la validation de la commande.'],
      ['Un transport pensé pour les entremets','Les mousses, crèmes et décors délicats demandent une température stable. Le gâteau est refroidi, protégé dans son écrin et maintenu au frais pendant le trajet. À réception, conservez-le entre 2 °C et 5 °C jusqu’à environ vingt minutes avant la dégustation.'],
      ['Anniversaire, cadeau ou réception familiale','Les formats 6, 8 et 12 parts répondent aux tablées les plus courantes à Salé. Pour une fiançailles, un mariage, un sbâa ou un événement accueillant davantage de convives, envoyez un brief sur mesure afin de réserver la capacité de l’atelier.']
    ],highlights:['Commande et créneau en ligne','Emballage protecteur','Paiement à la livraison disponible'],productIds:['pistache-fleur-doranger','caramel-majhul','atlas-chocolat'],
    faqs:[['Quel est le prix de la livraison de gâteau à Salé ?','La livraison standard coûte 35 DH. Le montant exact apparaît au checkout avant la validation.'],['Combien de temps à l’avance commander ?','Prévoyez 48 heures pour la collection et au moins sept jours pour une création personnalisée.'],['Puis-je payer à la livraison à Salé ?','Le règlement s’effectue en espèces à la réception ou par virement bancaire lorsque cette option est affichée.'],['Livrez-vous les gâteaux d’anniversaire à Salé ?','Oui. Choisissez un format de la collection ou envoyez un brief si vous souhaitez une décoration entièrement personnalisée.']],related:['/gateaux-rabat','/gateau-anniversaire-rabat','/gateau-sur-mesure-rabat'],ctaTitle:'Une douceur à faire livrer à Salé ?',ctaText:'Choisissez votre gâteau et consultez le prochain créneau disponible.'
  },
  {
    path:'/livraison-gateau-casablanca',metaTitle:'Livraison de gâteau à Casablanca | MoroKika Rabat',metaDescription:'Commandez un gâteau MoroKika livré à Casablanca : recettes artisanales, transport réfrigéré, créneau planifié et livraison offerte dès 450 DH.',region:'Casablanca',service:'Livraison réfrigérée de gâteaux',eyebrow:'Livraison de gâteaux · Casablanca',title:'Les créations MoroKika voyagent jusqu’à Casablanca.',intro:'Nos gâteaux sont préparés à Rabat puis conditionnés pour rejoindre Casablanca dans le respect de la chaîne du froid. La date et le créneau sont choisis au checkout afin que votre anniversaire, cadeau ou dîner arrive avec la fraîcheur attendue.',image:'/images/pistachio-blossom.webp',imageAlt:'Gâteau pistache et fleur d’oranger disponible en livraison à Casablanca',facts:[['Tarif standard','45 DH'],['Livraison offerte','Dès 450 DH'],['Préparation','48 h conseillées']],
    sections:[
      ['Une commande claire avant le départ de l’atelier','La fiche produit permet de choisir six, huit ou douze parts, puis d’ajouter un message. Au checkout, sélectionnez Casablanca, votre adresse et le créneau souhaité. La livraison standard est calculée à 45 DH sous 450 DH de panier et offerte à partir de ce seuil.'],
      ['Des recettes adaptées à une dégustation soignée','Pistache et fleur d’oranger, chocolat noir et noisette, rose et framboise ou datte Majhoul : la collection met en avant des parfums lisibles et une sucrosité mesurée. Le conditionnement limite les mouvements pendant le trajet et protège les finitions.'],
      ['Prévoir une livraison sereine à Casablanca','Commandez idéalement au moins 48 heures avant la date souhaitée. Renseignez une adresse complète et un téléphone joignable ; l’équipe peut ainsi confirmer les conditions du créneau. Pour un grand événement ou un décor personnalisé, le formulaire sur mesure reste la voie la plus adaptée.']
    ],highlights:['Transport au frais','Adresse et créneau confirmés','Livraison offerte dès 450 DH'],productIds:['pistache-fleur-doranger','atlas-chocolat','rose-framboise'],
    faqs:[['Quel est le tarif de livraison à Casablanca ?','La livraison standard est de 45 DH et devient offerte à partir de 450 DH de commande.'],['Les gâteaux sont-ils préparés le jour même ?','Chaque création est préparée à la commande selon son temps de prise et de finition, puis conservée au frais jusqu’au départ.'],['Puis-je choisir une date précise ?','Oui. Les dates et créneaux disponibles apparaissent pendant la commande.'],['Proposez-vous des gâteaux personnalisés à Casablanca ?','Oui, sous réserve de disponibilité et de faisabilité du transport. Envoyez votre brief au moins sept jours à l’avance.']],related:['/gateaux-rabat','/gateau-sur-mesure-rabat','/gateau-anniversaire-rabat'],ctaTitle:'MoroKika arrive à votre table à Casablanca.',ctaText:'Découvrez les créations disponibles et choisissez votre date de livraison.'
  },
  {
    path:'/livraison-gateau-temara',metaTitle:'Livraison de gâteau à Témara — 35 DH | MoroKika',metaDescription:'Commandez un gâteau artisanal livré à Témara : formats de 6 à 12 parts, transport au frais, créneau planifié et tarif standard de 35 DH.',region:'Témara',service:'Livraison de gâteaux',eyebrow:'Livraison de gâteaux · Témara',title:'Un gâteau MoroKika livré à Témara, sans bousculer votre journée.',intro:'MoroKika prépare votre gâteau à la commande dans son atelier d’Agdal, puis organise un trajet au frais vers Témara. Vous choisissez la recette, le nombre de parts, la date et votre message avant de valider un tarif de livraison clair.',image:'/images/vanilla-fig.webp',imageAlt:'Gâteau artisanal vanille et figue préparé pour une livraison à Témara',facts:[['Tarif standard','35 DH'],['Préparation','48 h conseillées'],['Formats collection','6, 8 ou 12 parts']],
    sections:[
      ['Choisir un format adapté à votre table','La collection propose trois repères simples : six parts pour une petite attention, huit pour un anniversaire familial et douze pour une tablée plus généreuse. Si le gâteau suit un repas complet, comptez une part par personne ; pour un goûter où il tient le premier rôle, prévoyez une petite marge.'],
      ['Planifier le trajet entre Rabat et Témara','Indiquez une adresse complète, un numéro joignable et le créneau souhaité au checkout. Le gâteau est refroidi avant son départ, placé dans un écrin rigide puis transporté sur une surface stable. La livraison standard à Témara coûte 35 DH, affichés avant la validation.'],
      ['Passer de la collection au sur-mesure','Une inscription courte peut être ajoutée à une création de la boutique. Pour une palette spécifique, un thème, un grand nombre d’invités ou une pièce de fiançailles, envoyez plutôt un brief au moins sept jours avant la réception afin que l’atelier confirme la faisabilité.']
    ],highlights:['Tarif annoncé avant paiement','Transport protégé et réfrigéré','Message personnalisé disponible'],productIds:['vanille-figue','rose-framboise','safran-agrumes'],
    faqs:[['Combien coûte la livraison d’un gâteau à Témara ?','Le tarif standard est de 35 DH. Le checkout affiche le montant avant la confirmation de la commande.'],['Quel délai faut-il prévoir ?','Commandez idéalement 48 heures à l’avance pour la collection et au moins sept jours avant pour une création sur mesure.'],['Puis-je commander un gâteau d’anniversaire à Témara ?','Oui. Les formats de la collection conviennent à de nombreux anniversaires ; un brief permet de demander un décor entièrement personnalisé.'],['Comment conserver le gâteau après réception ?','Gardez-le dans sa boîte au réfrigérateur entre 2 °C et 5 °C, puis suivez le temps de remise à température conseillé pour la recette.']],related:['/gateaux-rabat','/livraison-gateau-sale','/gateau-anniversaire-rabat'],ctaTitle:'Votre prochain gâteau peut arriver à Témara.',ctaText:'Choisissez une recette de la collection, un format et votre créneau de livraison.'
  },
  {
    path:'/livraison-gateau-kenitra',metaTitle:'Livraison de gâteau à Kénitra — 40 DH | MoroKika',metaDescription:'Faites livrer un gâteau MoroKika à Kénitra : préparation artisanale à Rabat, transport au frais, date planifiée et tarif standard de 40 DH.',region:'Kénitra',service:'Livraison réfrigérée de gâteaux',eyebrow:'Livraison de gâteaux · Kénitra',title:'De notre atelier de Rabat jusqu’à votre table à Kénitra.',intro:'Pour un anniversaire, un cadeau ou un déjeuner à Kénitra, MoroKika prépare chaque création sur commande et coordonne son départ avec le créneau choisi. Le conditionnement protège les textures et le décor pendant le trajet.',image:'/images/praline-coffee.webp',imageAlt:'Gâteau praliné café MoroKika disponible en livraison à Kénitra',facts:[['Tarif standard','40 DH'],['Délai conseillé','48 h minimum'],['Transport','Au frais et à plat']],
    sections:[
      ['Commander avec suffisamment d’avance','Le trajet vers Kénitra demande une organisation précise entre la finition du gâteau et sa remise. Réservez au moins 48 heures avant la date souhaitée pour une recette de la collection. Les week-ends et périodes de fête se remplissent plus vite ; un projet personnalisé mérite au moins sept jours.'],
      ['Connaître le montant avant de confirmer','Sélectionnez Kénitra dans le checkout puis renseignez votre adresse et un téléphone joignable. Le tarif standard de 40 DH apparaît dans le récapitulatif avant le paiement. L’équipe confirme ensuite le créneau selon la capacité de production et la tournée prévue.'],
      ['Préserver la fraîcheur jusqu’au service','À réception, posez la boîte à plat dans un réfrigérateur dégagé. Les mousses et crèmes sont conçues pour être dégustées fraîches mais pas glacées : sortez généralement le gâteau 15 à 25 minutes avant la découpe, selon l’indication donnée avec la commande.']
    ],highlights:['Créneau coordonné avec l’atelier','Écrin rigide pour le trajet','Recettes préparées à la commande'],productIds:['praline-cafe','atlas-chocolat','caramel-majhul'],
    faqs:[['Quel est le prix de livraison à Kénitra ?','La livraison standard coûte 40 DH. Le total est présenté dans le récapitulatif avant la validation.'],['Livrez-vous le jour même à Kénitra ?','Non. Un minimum de 48 heures est conseillé afin de préparer le gâteau et d’organiser le trajet au frais.'],['Quels formats peut-on faire livrer ?','La collection propose 6, 8 et 12 parts. Les formats plus grands sont étudiés sur demande selon les contraintes de transport.'],['Peut-on payer à la livraison ?','Le règlement s’effectue en espèces à la réception ou par virement bancaire lorsque cette option est affichée.']],related:['/gateaux-rabat','/livraison-gateau-sale','/livraison-gateau-casablanca'],ctaTitle:'Une occasion à célébrer à Kénitra ?',ctaText:'Choisissez votre gâteau et réservez une date compatible avec la prochaine tournée.'
  },
  {
    path:'/gateau-sbaa-rabat',metaTitle:'Gâteau de sbâa et naissance à Rabat | MoroKika',metaDescription:'Préparez un gâteau de sbâa ou de naissance à Rabat : format selon vos invités, décor personnalisé, saveurs délicates et livraison planifiée.',region:'Rabat-Salé-Témara',service:'Gâteaux de sbâa et de naissance',eyebrow:'Sbâa & naissance · Rabat',title:'Un gâteau de sbâa délicat pour accueillir une nouvelle histoire.',intro:'Le sbâa réunit la famille autour d’un moment tendre, souvent préparé en quelques jours très intenses. MoroKika vous aide à choisir un format, une palette et des parfums faciles à partager, puis coordonne la préparation avec la date de la réception.',image:'/images/rose-raspberry.webp',imageAlt:'Gâteau rose et framboise MoroKika pour une célébration de naissance à Rabat',facts:[['Délai sur mesure','7 jours conseillés'],['Formats collection','6, 8 ou 12 parts'],['Livraison','Rabat, Salé et Témara']],
    sections:[
      ['Commencer par les invités et le moment du service','Indiquez le nombre d’adultes et d’enfants, l’heure du sbâa et les autres douceurs prévues. Après un repas ou à côté d’un assortiment de pâtisseries, les parts peuvent rester modérées. Pour un goûter centré sur le gâteau, une marge supplémentaire évite de compter trop juste.'],
      ['Créer un décor doux et personnel','Une teinte ivoire, rose poudré, sauge, ciel ou sable peut être associée au prénom, à une courte formule ou à un motif sobre. Partagez vos références et les couleurs de la table dans le brief. L’atelier adapte ensuite l’idée à une finition pâtissière stable, lisible et fidèle au style MoroKika.'],
      ['Choisir des parfums qui rassemblent','Vanille et figue, pistache et fleur d’oranger, framboise et rose ou agrumes au safran offrent des profils différents sans être excessivement sucrés. Mentionnez les préférences de la famille et toute allergie dès le premier échange afin de recevoir une recommandation appropriée.'],
      ['Organiser le retrait ou la livraison','Le retrait à Agdal est gratuit sur créneau confirmé. Une livraison peut être planifiée vers Rabat, Salé ou Témara selon la date et le format. Prévoyez une personne joignable à l’arrivée et une tablette dégagée au réfrigérateur pour conserver l’écrin bien à plat.']
    ],highlights:['Format conseillé selon la réception','Prénom ou message personnalisé','Transport au frais sur créneau'],productIds:['rose-framboise','pistache-fleur-doranger','vanille-figue'],
    faqs:[['Quand commander un gâteau de sbâa à Rabat ?','Pour une création personnalisée, contactez l’atelier dès que la date est connue et prévoyez idéalement sept jours.'],['Peut-on ajouter le prénom du bébé ?','Oui. Indiquez le prénom, l’orthographe exacte et la formule souhaitée dans votre brief.'],['Quels parfums conviennent à une grande famille ?','Les profils vanille-figue, pistache-fleur d’oranger et rose-framboise sont des options équilibrées ; l’atelier vous conseille selon le menu.'],['Livrez-vous un gâteau de naissance à Salé ou Témara ?','La livraison peut être organisée à Rabat, Salé et Témara selon le créneau, le format et la capacité de l’atelier.']],related:['/gateau-sur-mesure-rabat','/gateaux-rabat','/livraison-gateau-sale'],ctaTitle:'Préparons cette douce bienvenue.',ctaText:'Partagez la date, le nombre d’invités, le prénom et les couleurs imaginées.'
  },
  {
    path:'/gateaux-entreprise-rabat',metaTitle:'Gâteaux pour entreprises et équipes à Rabat | MoroKika',metaDescription:'Commandez un gâteau pour une équipe, un client ou un événement professionnel à Rabat : formats adaptés, message personnalisé et livraison.',region:'Rabat-Salé',service:'Gâteaux pour entreprises et événements professionnels',eyebrow:'Entreprises & équipes · Rabat',title:'Des gâteaux pour remercier, réunir et célébrer votre équipe.',intro:'Pot de départ, lancement, réussite collective, accueil d’un client ou cadeau professionnel : MoroKika prépare à Rabat des créations élégantes, faciles à présenter et dimensionnées selon le nombre de personnes.',image:'/images/story-table.webp',imageAlt:'Gâteau MoroKika présenté sur une table pour un événement professionnel à Rabat',facts:[['Projets personnalisés','7 jours conseillés'],['Formats','Collection ou sur mesure'],['Coordination','Adresse et créneau confirmés']],
    sections:[
      ['Définir l’usage avant de choisir le gâteau','Un gâteau servi pendant une réunion ne se dimensionne pas comme un cadeau remis dans son écrin. Précisez le nombre de personnes, le moment de dégustation, la présence d’autres desserts et les contraintes du lieu. L’atelier peut alors recommander un format de collection ou étudier une composition plus généreuse.'],
      ['Personnaliser sans surcharger','Les couleurs de votre univers, un mot de remerciement, une date ou une formule courte suffisent souvent à créer une attention mémorable. Pour un projet de marque, transmettez une palette et les éléments autorisés ; MoroKika propose une interprétation sobre compatible avec ses techniques et son identité visuelle.'],
      ['Choisir une recette accessible à l’équipe','Un profil chocolat-praliné convient aux amateurs de saveurs intenses ; pistache-fleur d’oranger apporte une signature marocaine ; agrumes-safran offre une finale plus fraîche. Signalez les allergènes et préférences alimentaires connus, tout en gardant à l’esprit que l’atelier ne garantit pas l’absence de traces croisées.'],
      ['Coordonner la remise au bureau','Communiquez l’adresse complète, l’étage, les conditions d’accès, le nom du contact et un téléphone joignable. Le gâteau voyage au frais dans son écrin. À l’arrivée, prévoyez une surface plane au réfrigérateur et le matériel nécessaire pour une découpe nette au moment choisi.']
    ],highlights:['Conseil sur le nombre de parts','Message professionnel personnalisé','Livraison planifiée au bureau'],productIds:['atlas-chocolat','pistache-fleur-doranger','praline-cafe'],
    faqs:[['Quel délai prévoir pour un gâteau d’entreprise à Rabat ?','Prévoyez 48 heures pour une création de la collection et au moins sept jours pour un format ou un décor personnalisé.'],['Pouvez-vous reprendre les couleurs de notre marque ?','Vous pouvez transmettre votre palette. L’atelier propose ensuite une interprétation élégante selon la faisabilité pâtissière.'],['Comment choisir le nombre de parts pour une équipe ?','Indiquez l’effectif, l’heure de service et les autres desserts prévus ; MoroKika vous recommande le format adapté.'],['La livraison au bureau est-elle possible ?','Oui à Rabat, et selon le projet à Salé. Fournissez les informations d’accès et un contact disponible sur le créneau.']],related:['/gateaux-rabat','/gateau-sur-mesure-rabat','/livraison-gateau-sale'],ctaTitle:'Une équipe à célébrer à Rabat ?',ctaText:'Décrivez l’occasion, l’effectif et le lieu afin de recevoir une recommandation claire.'
  }
]

export const commerceLandingPages = [
  {path:'/boutique',metaTitle:'Gâteaux artisanaux marocains en ligne | MoroKika',metaDescription:'Découvrez les gâteaux artisanaux MoroKika : pistache, chocolat, fruits et saveurs marocaines, disponibles en 6, 8 ou 12 parts.',title:'Tous les gâteaux MoroKika',eyebrow:'La boutique',image:'/images/berry-cheesecake.webp',productIds:'all'},
  {path:'/collections/signatures',metaTitle:'Gâteaux signature aux saveurs marocaines | MoroKika',metaDescription:'Pistache, fleur d’oranger, dattes Majhoul, café et chocolat : découvrez les créations signature préparées à Rabat par MoroKika.',title:'Nos signatures',eyebrow:'Les icônes MoroKika',image:'/images/pistachio-blossom.webp',productIds:['pistache-fleur-doranger','caramel-majhul','atlas-chocolat','praline-cafe']},
  {path:'/collections/anniversaires',metaTitle:'Collection de gâteaux d’anniversaire | MoroKika',metaDescription:'Choisissez un gâteau d’anniversaire artisanal en 6, 8 ou 12 parts, avec message personnalisé et livraison planifiée.',title:'Joyeux anniversaire',eyebrow:'Un vœu gourmand',image:'/images/rose-raspberry.webp',productIds:['pistache-fleur-doranger','rose-framboise','cheesecake-fruits-rouges','vanille-figue']},
  {path:'/collections/cadeaux',metaTitle:'Gâteaux cadeaux et petites attentions | MoroKika',metaDescription:'Offrez un gâteau artisanal dans son écrin MoroKika, accompagné d’un petit mot et livré à la date choisie.',title:'Petites attentions',eyebrow:'À offrir avec le cœur',image:'/images/atlas-chocolate.webp',productIds:['atlas-chocolat','caramel-majhul','praline-cafe','pistache-fleur-doranger']}
]
